### ISSUE TITLE
Debian installation

### ISSUE THREAD

**Issue by Neustradamus** [openairplay/airplay2-receiver#19]
Originally: https://github.com/ckdo/airplay2-receiver/issues/9

@noelhibbard commented Jan 18, 2021 •

Here are the steps I did to get this running on Debian in case anyone is interested:

sudo apt install -y libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev portaudio19-dev python3 python3-pip python3-pyaudio build-essential pkg-config git alsa-utils
git clone https://github.com/ckdo/airplay2-receiver.git
cd airplay2-receiver/
pip3 install virtualenv
virtualenv airplay2-receiver
cd airplay2-receiver/
pip3 install -r ../requirements.txt
pip3 install pyaudio

**Comment by XericZephyr** [comment]
Could we just use docker on Debian?

**Comment by systemcrash** [comment]
Seems legit. Others seem to have succeeded doing so.
