### ISSUE TITLE
Crash if IPv6 is not available

### ISSUE THREAD

**Issue by Neustradamus** [openairplay/airplay2-receiver#21]
Originally: https://github.com/ckdo/airplay2-receiver/issues/12

@oxixes commented Mar 2, 2021

My wifi adapter does not offer an IPv6, and the program crash on startup, I solved the issue by just commenting the IPv6 part on the code and removing it from sonos_one_setup, but I think it should be done better.

**Comment by systemcrash** [comment]
I think this is fixed with #31
