### ISSUE TITLE
Issues running on Apple Silicon (ARM64 Native)

### ISSUE THREAD

**Issue by M-Whitaker** [openairplay/airplay2-receiver#24]
Testing on my M1 MacBook Pro, I can see a problem installing pynacl due to its dependency on cffi which seems to not build properly in the python wheel as documented pyca/pynacl#654. Of course this does not take into account of simply running in Rosetta.

**Comment by systemcrash** [comment]
Please try current master :)

**Comment by M-Whitaker** [comment]
All working now: @ https://github.com/openairplay/airplay2-receiver/commit/984a98cb34c6fc98729719144658a536639df844

:)
