### ISSUE TITLE
Server Not Showing up on iPhone

### ISSUE THREAD

**Issue by MasterCubo** [openairplay/airplay2-receiver#56]
Hello, I know this is probably a stupid question, but how did you or any other successful users obtain your interface GUID? I'm not sure where to start. I'm on Windows 10.

**Comment by MasterCubo** [comment]
I found one available network interface that contained my IPv6 address, but when I went to use it, it said [Network interface not found.]

**Comment by MasterCubo** [comment]
And again, sorry for the update, but I found the problem, and put the GUID in brackets, but now the server isn't showing up on my iPhone. :/  They appear to be on the same IP.

**Comment by systemcrash** [comment]
GUID is randomly generated. Same IP = bad....

**Comment by dinpau** [comment]
Same problem here, specified the GUID with brackets but my Iphone cannot find the server

**Comment by systemcrash** [comment]
Not enough info. I don't even understand the first issue anything more than "it doesn't work for me". This could be anything - but the first I'd check is whether the ZeroConf messages are sent out from the broadcasting host, at least.

**Comment by systemcrash** [comment]
I'm closing this without further info or logs. I know this for a fact: specifying a GUID where there should be an IP will not get you anywhere. mDNS broadcasts the chosen IP, not its GUID. Use `--list-interfaces` to query the available ones. 

If anyone else has useful info for this (esp on Windoze), please re-open this.

**Comment by chrislanzl** [comment]
My guess. Confusion came from the README not mentioning what's in your last comment.

Maybe updating it like this:

`
pip install pipwin pycaw
pipwin install pyaudio

python ap2-receiver.py --list-interfaces (identify the GUID of the network interface to be used by receiver)

python ap2-receiver.py -m myap2 -n [YOUR_INTERFACE_GUID] (looks like this for instance {02681AC0-AD52-4E15-9BD6-8C6A08C4F836} )
`
