### ISSUE TITLE
Issue when running code?

### ISSUE THREAD

**Issue by JayLindblad** [openairplay/airplay2-receiver#59]
I wanna preface by saying I know absolutely nothing about coding or installing shit, but I've gotten this far and received a syntax error when trying to run ap2-receiver.py.

I type in:

python ap2-receiver.py -m myap2 --netiface=en0"

It spits out:

File "ap2-receiver.py", line 326
    "features": f"{hex(FEATURES & 0xffffffff)},{hex(FEATURES >> 32 & 0xffffffff)}",

SyntaxError: invalid syntax

(it had a carat pointing to the last double-quote (after the curly bracket))

I hope this helps maybe?? I don't know if it would be helpful to put some more info like what I'm running on or what.

**Comment by systemcrash** [comment]
Yeah, you ran python, and possibly not python3. Older versions of python probably don't understand f strings. 

So, get yourself python 3 - at least version 3.6... preferably something newer.
