### ISSUE TITLE
Error streaming from iPhone

### ISSUE THREAD

**Issue by Kunitomi-IBM** [openairplay/airplay2-receiver#60]
I installed airplay2-receiver on both:
1. 2018 Macbook Pro running Big Sur 11.6.2
2. 2014 Mac Mini running running Monterey 12.1

for both installs I am able to connect my iPhone (iOs 15.2) via airplay. However, once I start streaming I get the following error:

[Audio.Main]: RTP ChaCha20_Poly1305 decrypt: ValueError('MAC check failed')

>python ap2-receiver.py -m myap2 --netiface=en0
[Receiver]: Enabled features: 0001c300405f4200
[Receiver]: Feat.Ft48TransientPairing|Ft47PeerMgmt|Ft46HKPairing|Ft41_PTPClock|Ft40BufferedAudio|Ft30UnifiedAdvertInf|Ft22AudioUnencrypted|Ft20RcvAudAAC_LC|Ft19RcvAudALAC|Ft18RcvAudPCM|Ft17AudioMetaTxtDAAP|Ft16AudioMetaProgres|Ft14MFiSoft_FairPlay|Ft09AirPlayAudio
[Receiver]: Interface: en0
[Receiver]: Mac: f0:18:98:38:a9:94
[Receiver]: IPv4: 192.168.68.116
[Receiver]: IPv6: fe80::4e:3d75:354a:dfae
[Receiver]: 
[asyncio]: Using selector: KqueueSelector
[Receiver]: mDNS service registered
[Receiver]: Starting RTSP server, press Ctrl-C to exit...
[Receiver]: serving at port 7000
[Receiver]: Opened connection from 192.168.68.124:54885
[Receiver]: {'qualifier': ['txtAirPlay']}
[Receiver]: Sending our device info
[Receiver]: SETUP: rtsp://192.168.68.116/367695622011766926
[Receiver]: 
[Receiver]: GET_PARAMETER: rtsp://192.168.68.116/367695622011766926
[Receiver]: GET_PARAMETER: b'volume'
[Receiver]: RECORD: rtsp://192.168.68.116/367695622011766926
[Receiver]: SETPEERS: rtsp://192.168.68.116/367695622011766926
[Receiver]: ['192.168.68.124', 'fe80::1852:8e1a:5388:12dd']
[Receiver]: TEARDOWN: rtsp://192.168.68.116/367695622011766926
[Receiver]: {}
[Receiver]: Opened connection from 192.168.68.124:54897
[Receiver]: {'qualifier': ['txtAirPlay']}
[Receiver]: Sending our device info
[Receiver]: SETUP: rtsp://192.168.68.116/5351491092943162614
[Receiver]: 
[Receiver]: GET_PARAMETER: rtsp://192.168.68.116/5351491092943162614
[Receiver]: GET_PARAMETER: b'volume'
[Receiver]: RECORD: rtsp://192.168.68.116/5351491092943162614
[Receiver]: SETPEERS: rtsp://192.168.68.116/5351491092943162614
[Receiver]: ['192.168.68.124', 'fe80::1852:8e1a:5388:12dd']
[Receiver]: SETUP: rtsp://192.168.68.116/5351491092943162614
[Receiver]: 
[Receiver]: FLUSH: rtsp://192.168.68.116/5351491092943162614
[Audio.Main]: Total sample_delay (sec): 0.12676
[Audio.Main]: RTP ChaCha20_Poly1305 decrypt: ValueError('MAC check failed')

**Comment by systemcrash** [comment]
I think you're streaming a real-time stream, type 96, e.g. something like Spotify. I fixed this, but have not pushed it out yet.

**Comment by systemcrash** [comment]
Actually, no, it's already out there. It's fixed by 55833b53210116831abeebd0a63dacbbe6949b45
Update to the latest, and it should be fixed. Otherwise, please run with `--debug`, so we can see what's going on.
