### ISSUE TITLE
Starting but not discovered on network

### ISSUE THREAD

**Issue by corrpel** [openairplay/airplay2-receiver#7]
Hi,
I am trying to use it, i got to the part:
```
mDNS service registered
Starting RSTP server, press Ctrl-C to exit...
serving at port 7000
```
But i cannot find it on my phone
I am using IOS 14.4, raspberry pi zero with wlan0 interface.
Maybe i need to install some other dependecy?!
Thank you.

**Comment by systemcrash** [comment]
Can u ping your iphone from the Pi?

**Comment by corrpel** [comment]
Yes, i have replies from iphone when i ping it.

**Comment by corrpel** [comment]
Also, when i use avahi-browse -a -k on another computer, i can see all the other devices, including two homepods that i have connected via wifi, and my phone, but if i launch the aiplay2-receiver, the device does not appear in the result(i think it should broadcast the name like this: "Left  _airplay._tcp local").
Left is one of the homepods in this example.

**Comment by corrpel** [comment]
Hmm, looks like it is a problem with my device, since raspberrypi.local is not resolved also, running avahi-daemon.
I think this can pe closed.

**Comment by dustinlieu** [comment]
I had the same problem. The problem was that avahi-daemon was advertising the docker0's IP instead of wlan0's IP. I fixed it by adding the line `deny-interfaces=docker0` to docker/avahi-daemon.conf.

**Comment by corrpel** [comment]
Thanks for the tip. I am not using docker, and i’ve managed to use it on another machine.
