### ISSUE TITLE
[Windows 11 Home] Airplay receiver not visible to other devices

### ISSUE THREAD

**Issue by rascheln** [openairplay/airplay2-receiver#83]
### The problem

Hello,

I am grateful that you provided a function to list the device GUID's.  I believe I found the correct device interface GUID, and received confirmation that the server is supposedly working:
`[Receiver]: serving on [local IP]`
However, I do not see any airplay server being broadcast via my iPad Pro. The "Screen Mirroring" list remains empty. I tested this out with LonelyScreen and I indeed still get that to successfully broadcast.

Are there any additional security settings that I should investigate, when running these commands?

### What commit exhibits the issue?

07195c5

### What type of installation are you running?

direct (via `python3`)

### With which python3 version do you run Receiver?

3.10.7

### OS the receiver runs on

Windows 11 Home Version 21H2

### OS the sender runs

iOS 16.2; iPad OS 16.3

### Which sender client was used

[screen mirroring]

### Command invocation

python ap2-receiver.py -m myap2 -n "{device GUID here}"

**Comment by systemcrash** [comment]
ScreenMirroring list likely will remain empty. 

Until such a time as someone writes a dummy screen receiver.

ScreenMirroring is a different beast from audio only. It's also kind of redundant if audio only is always available via airplay.
