### ISSUE TITLE
Windows Network interface not found

### ISSUE THREAD

**Issue by giulio333** [openairplay/airplay2-receiver#88]
### The problem

Why I received this error? I tried all network interface GUID

### What commit exhibits the issue?

6c343d3

### What type of installation are you running?

virtualenv

### With which python3 version do you run Receiver?

python 3.11.4

### OS the receiver runs on

windows

### OS the sender runs

windows 11

### Command invocation

python ap2-receiver.py -m myap2 -n [GUID]

**Comment by Neustradamus** [comment]
@systemcrash: What do you think?

**Comment by systemcrash** [comment]
Run with the switch to determine which GUID are available.

**Comment by giulio333** [comment]
I have already tried and tried to launch using all available GUID, but it’s not working

**Comment by systemcrash** [comment]
Which windows 11 version number?

Hmm, windows works for some. If you'd like to spend some time to investigate why, you can submit a PR if you find the problem. I do not run windows, so will never be able to investigate further.

**Comment by giulio333** [comment]
I have Windows 11 22H2 (build SO 22621.2715)

**Comment by djsomi** [comment]
Try like this with quotes: "{02681AC0-AD52-4E15-9BD6-8C6A08C4F836}"

**Comment by Aliceljm1** [comment]
> Try like this with quotes: "{02681AC0-AD52-4E15-9BD6-8C6A08C4F836}"

This is the correct answer, my command line is as follows ：python ap2-receiver.py -m myap2 -n "{94B8CFE9-D19C-4AB7-AD02-A66DD00328B7}"

**Comment by giulio333** [comment]
I’ll try as soon as possible, although I think I’ve already tried with this command

**Comment by giulio333** [comment]
this worked for me python ap2-receiver.py -m myap2 -n "{94B8CFE9-D19C-4AB7-AD02-A66DD00328B7}"
Thank you!

**Comment by djsomi** [comment]
> this worked for me python ap2-receiver.py -m myap2 -n "{94B8CFE9-D19C-4AB7-AD02-A66DD00328B7}" Thank you!

Welcome :)
